name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_RELEASE_RSODX }}
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v3
        with:
          release-type: ruby

